version: 2
jobs:
  # build job omitted for brevity
  build:
    working_directory: /tmp/vasko
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - deploy:
          name: Deploy to S3
          command: aws s3 sync /tmp/vasko s3://postease-sample.com/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
